apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-neo4j-ingress
  namespace: neo4j
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "prod-autopilot-us-central-ip"
    networking.gke.io/managed-certificates: "mcp-neo4j-cert"
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - hosts:
    - INGRESS_HOST
    secretName: mcp-neo4j-cert-secret
  rules:
  - host: INGRESS_HOST
    http:
      paths:
      - path: /v1/neo4j/cypher/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: mcp-neo4j-cypher
            port:
              number: 8001
      - path: /v1/neo4j/memory/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: mcp-neo4j-memory
            port:
              number: 8002
      - path: /v1/neo4j/modeling/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: mcp-neo4j-data-modeling
            port:
              number: 8004
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: mcp-neo4j-cert
  namespace: neo4j
spec:
  domains:
    - INGRESS_HOST